//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Class_Relax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Students = new HashSet<Student>();
        }
    
        public long ClassPin { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> NumOfStudents { get; set; }
        public Nullable<double> ClassAvgFeedback { get; set; }
        public int IDVideo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int UserID { get; set; }
        public int Duration { get; set; }
        public string Type { get; set; }
        public string Style { get; set; }
    
        public virtual User User { get; set; }
        public virtual Video Video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
