//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Class_Relax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string Nickname { get; set; }
        public long ClassPin { get; set; }
        public string Mood { get; set; }
        public Nullable<int> Feedback { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
